services:
  - type: web
    name: visiocar-api
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://voluble-biscotti-0d950f.netlify.app
      - key: SUPABASE_URL
        value: https://dpgzrymeqwwjpoxoiwaf.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_ATYFiiMT19IEPLdlxRMeug_3kqTsyQD
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: sb_publishable_ATYFiiMT19IEPLdlxRMeug_3kqTsyQD
      - key: JWT_SECRET
        generateValue: true